# Generated by Django 5.1.1 on 2024-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="static/img/Logo-pink.png", upload_to=""
            ),
        ),
    ]
