# Generated by Django 5.1.3 on 2024-11-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_itemimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemImages',
        ),
    ]
